version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.8.2-browsers

    working_directory: ~/eviction-hearing-parser
  
    steps:
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest tests/
