jobs:
  build:
    docker:
      - image: circleci/python:3.8.5-browsers
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest
            pip install pytest-cov
            pip install coveralls
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            pytest --cov=. --cov-report=term-missing
            coveralls
workflows:
  orbs:
    browser-tools: circleci/browser-tools@1.1.1
  version: 2.1
  build_and_test:
    jobs:
      - build
